// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdf3FSEkNDz6zor_STy7GynSgQ_N4ksNo',
    appId: '1:263661068265:web:90f82d55dc839993253578',
    messagingSenderId: '263661068265',
    projectId: 'flutter-72e12',
    authDomain: 'flutter-72e12.firebaseapp.com',
    storageBucket: 'flutter-72e12.appspot.com',
    measurementId: 'G-GS0VC43MWT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEH3tbJxQcXVbStH2Q_6di9CiOOoFaepc',
    appId: '1:263661068265:android:639a014e2a5f0925253578',
    messagingSenderId: '263661068265',
    projectId: 'flutter-72e12',
    storageBucket: 'flutter-72e12.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC391QNffHFxTihAoeCOkAi4BLHHU0bi74',
    appId: '1:263661068265:ios:5d7d5d0c76e9d32f253578',
    messagingSenderId: '263661068265',
    projectId: 'flutter-72e12',
    storageBucket: 'flutter-72e12.appspot.com',
    androidClientId: '263661068265-otinl2vlfrbmnpgbde0epqkipq4ka3bf.apps.googleusercontent.com',
    iosClientId: '263661068265-vb6a3t0t946l61hrq22plvj48t9ii45n.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutter2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC391QNffHFxTihAoeCOkAi4BLHHU0bi74',
    appId: '1:263661068265:ios:5d7d5d0c76e9d32f253578',
    messagingSenderId: '263661068265',
    projectId: 'flutter-72e12',
    storageBucket: 'flutter-72e12.appspot.com',
    androidClientId: '263661068265-otinl2vlfrbmnpgbde0epqkipq4ka3bf.apps.googleusercontent.com',
    iosClientId: '263661068265-vb6a3t0t946l61hrq22plvj48t9ii45n.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutter2',
  );
}
